binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where


  import Import

'
extensions:
  TemplateHaskell: true
  OverloadedStrings: true
  QuasiQuotes: true
  TypeFamilies: true
  MultiParamTypeClasses: true
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args:
- -Wall
excluded-modules:
- Setup.hs
